name: test-actions-job1
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello World!! From Step-1"
      - name: step2
        run: echo "Hello World!! From Step-2"
      - name: step3
        run: echo "Hello World!! From Step-3 and 4"
